#! /bin/bash
SCRIPT_PATH=$(pwd)
TEMPLATE_PATH=$SCRIPT_PATH/template
LIB_PATH=$SCRIPT_PATH/lib

MYSQL_HOST=127.0.0.1
MYSQL_USER=root
MYSQL_PASSWORD=xiandao2015
MYSQL_CONN=mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_HOST

RABBITMQ_HOST=127.0.0.1
RABBITMQ_USER=openstack
RABBITMQ_PASSWORD=xiandao2015

KEYSTONE_DBNAME=keystone
KEYSTONE_DBPASS=xiandao2015
MYSQL_HOST=127.0.0.1

PUBLICURL=http://localhost:5000/v2.0
ADMINURL=http://localhost:35357/v2.0
INTERNALURL=http://localhost:5000/v2.0
ADMIN_PASSWORD=xiandao2015
DEMO_PASSWORD=xiandao2015

sudo add-apt-repository -y cloud-archive:liberty
sudo apt-get update

source $LIB_PATH/database 
source $SCRIPT_PATH/func
source $LIB_PATH/keystone


