#! /bin/bash
STACK_USER=stack
USER_GROUP=stack

SCRIPT_PATH=$(pwd)
TEMPLATE_PATH=$SCRIPT_PATH/template
LIB_PATH=$SCRIPT_PATH/lib

MYSQL_HOST=127.0.0.1
MYSQL_USER=root
MYSQL_PASSWORD=xiandao2015
MYSQL_CONN=mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_HOST

RABBITMQ_HOST=127.0.0.1
RABBITMQ_USER=openstack
RABBITMQ_PASSWORD=xiandao2015

KEYSTONE_DBNAME=keystone
KEYSTONE_DBPASS=xiandao2015
MYSQL_HOST=127.0.0.1

KEYSTONE_PUBLICURL=http://localhost:5000/v2.0
KEYSTONE_ADMINURL=http://localhost:35357/v2.0
KEYSTONE_INTERNALURL=http://localhost:5000/v2.0
ADMIN_PASSWORD=xiandao2015
DEMO_PASSWORD=xiandao2015

sudo add-apt-repository -y cloud-archive:liberty
sudo apt-get update

source $LIB_PATH/database 
source $SCRIPT_PATH/func
source $LIB_PATH/keystone

#swift, depend on functions in func script.
source keyrc
tenant_id=$(get_project_id admin)

SWIFT_PUBLICURL=http://localhost:8080/v1/AUTH_${tenant_id}
SWIFT_INTERNALURL=http://localhost:8080/v1/AUTH_${tenant_id}
SWIFT_ADMINURL=http://localhost:8080
SWIFT_PASSWORD=xiandao2015

TOP_DIR=$(cd $(dirname "$0") && pwd)
SWIFT_DATA_PATH=$TOP_DIR/swift_data

SWIFT_DISK_IMAGE=$SWIFT_DATA_DIR/drives/images/swift.img
SWIFT_LOOPBACK_DISK_SIZE=9663676416

SWIFT_REPLICAS=1
source $LIB_PATH/swift
