#!/bin/bash

# Usage: create_service <name> <type> <description>
function create_service {
	openstack service create --description="$3" --name $1 $2 
}

# Usage: create_endpoint <service> <region> <publicurl> <adminurl> <internalurl>
function create_endpoint {
	openstack endpoint create --publicurl $3 --internalurl $5 --adminurl $4 --region $2 $1
}

#Usage: create_project <project> <description>
function create_project {
	openstack project create --description "$2" $1
}

#Usage: get_project_id <project-name>
function get_project_id {
	openstack project show $1 -f value -c id
}

#Usage create_user <user> <passwd>
function create_user {
	openstack user create --password $2 $1
}

#Usage create_role <role>
function create_role {
	openstack role create $1
}

#Usage add_user_project_role <user> <project> <role>
function add_user_project_role {
	openstack role add --project $2 --user $1 $3
}


