#! /bin/bash

function mysql_add_keystone {
	mysql_cmd "CREATE DATABASE $KEYSTONE_DBNAME;"
	mysql_cmd "GRANT ALL PRIVILEGES ON $KEYSTONE_DBNAME.* TO '$KEYSTONE_DBNAME'@'localhost' IDENTIFIED BY '$KEYSTONE_DBPASS';"
	mysql_cmd "GRANT ALL PRIVILEGES ON $KEYSTONE_DBNAME.* TO '$KEYSTONE_DBNAME'@'%' IDENTIFIED BY '$KEYSTONE_DBPASS';"
	mysql_cmd "FLUSH PRIVILEGES;"
}

function install_keystone {
	echo "manual" | sudo tee /etc/init/keystone.override
	sudo apt-get install -y python-mysqldb memcached python-memcache keystone apache2 libapache2-mod-wsgi python-openstackclient
}

function config_keystone {
	sudo cp $TEMPLATE_PATH/keystone.conf /etc/keystone/keystone.conf
	sudo keystone-manage db_sync
}

function config_mod-wsgi_keystone {
	sudo cp $TEMPLATE_PATH/wsgi-keystone.conf.template /etc/apache2/sites-available/wsgi-keystone.conf 
	sudo ln -s /etc/apache2/sites-available/wsgi-keystone.conf /etc/apache2/sites-enabled 
	sudo mkdir -p /var/www/cgi-bin/keystone
	sudo cp $TEMPLATE_PATH/keystone-wsgi-admin /var/www/cgi-bin/keystone/admin
	sudo cp $TEMPLATE_PATH/keystone-wsgi-public /var/www/cgi-bin/keystone/main
	sudo chown -R keystone:keystone /var/www/cgi-bin/keystone
	sudo chmod 755 /var/www/cgi-bin/keystone/*

	sudo service apache2 restart
}

function create_service_and_endpoint {
	create_service keystone identity "OpenStack Identity"
	create_endpoint identity RegionOne $KEYSTONE_PUBLICURL $KEYSTONE_ADMINURL $KEYSTONE_INTERNALURL
	
	# Admin Project
	create_project admin "Admin Project"
	create_user admin $ADMIN_PASSWORD
	create_role admin
	add_user_project_role admin admin admin

	#Service Project
	create_project service "Service Project"
	
	#Demo Project
	create_project demo "Demo Project"
	create_user demo $DEMO_PASSWORD
	create_role user
	add_user_project_role demo demo user
}
